<Project Sdk="Microsoft.NET.Sdk">
    <!-- .NET Config -->
    <PropertyGroup>
        <RootNamespace>CmdRouter.Example</RootNamespace>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <!--Avoid fatal error: 'The library 'libhostpolicy.so' required'.-->
        <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    </PropertyGroup>
</Project>
