from cmd_router.lib.commands.context import ParseError
from cmd_router.utils import LazyServer, Status

from .context import lazy_suggest_srv_ctx as lazy_suggest_srv_ctx

__all__ = ["lazy_suggest_srv_ctx", "LazySuggestionsServer"]

class LazySuggestionsServer(LazyServer):
    @staticmethod
    def _disabled() -> bool: ...
    @staticmethod
    def _err(what: str) -> Status: ...
    def _send_json_list(self, suggestions: list[str]) -> Status | None: ...
    def _unsupported(self) -> Status: ...
    def do_PUT(self) -> Status: ...
    def do_DELETE(self) -> Status: ...
    def do_PATCH(self) -> Status: ...
    def do_HEAD(self) -> Status: ...
    def do_OPTIONS(self) -> Status: ...
    def _read_post_body(self) -> tuple[str | None, Status | None]: ...
    def _request_input(self, body_text: str) -> str: ...
    @staticmethod
    def _immediate_suggestions(error: ParseError) -> list[str]: ...
    def _compute_suggestions(self, command_text: str) -> tuple[list[str] | None, Status | None]: ...
    def do_POST(self) -> Status: ...
    def do_GET(self) -> Status: ...
