from typing import Final

from _typeshed import Incomplete

__all__ = ["lazy_suggest_srv_ctx"]

class _LazySuggestionsServerContext:
    _address: str
    _port: int
    _suggestions: list[str]
    _last_input: str | None
    _lock: Incomplete
    def __init__(self) -> None: ...
    @property
    def address(self) -> str: ...
    @address.setter
    def address(self, value: str) -> None: ...
    @property
    def port(self) -> int: ...
    @port.setter
    def port(self, value: int) -> None: ...
    def set_suggestions(self, suggestions: list[str], last_input: str | None = None) -> None: ...
    def get_suggestions(self) -> list[str]: ...
    def clear(self) -> None: ...
    @property
    def last_input(self) -> str | None: ...

lazy_suggest_srv_ctx: Final[_LazySuggestionsServerContext]
