[project]
name = "command-router"
version = "26.0-dev"
requires-python = ">=3.14"
license = "BSD-3-Clause-Clear"
authors = [
    { name = "Ian Hylton", email = "dcxrpse@krwwstudios.com" }
]
description = "Small, Brigadier-inspired command router."
readme = "README.md"
dependencies = [
    "black>=26.5.1",
    "click>=8.4.2",
    "icecream>=2.2.0",
    "json5>=0.15.0",
    # The only reason to add `mypy` was because of `stubgen`.
    # Do not use `mypy` for anything else, if not at all.
    "mypy>=2.3.1",
    "prompt-toolkit>=3.0.53",
    "pytest>=9.1.1",
    "rapidfuzz>=3.14.6",
    "ruff>=0.15.22",
    "rust-just>=1.57.0",
    "textual>=8.2.8",
    "ty>=0.0.77",
]

[project.urls]
Repository = "https://gitlab.com/denniscxrpse/command-router"
Issues = "https://gitlab.com/denniscxrpse/command-router/-/work_items"
# Documentation = "https://gitlab.com/denniscxrpse/

[tool.black]
line-length = 120
target-version = ['py314']

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.pyrefly]
project-includes = [
    "**/*.py*",
    "**/*.ipynb",
]
