from collections.abc import Callable
from typing import Any

from _typeshed import Incomplete
from textual.app import App, ComposeResult
from textual.events import Key, Resize
from textual.widgets import Input

from cmd_router.lib.control import ControlResult
from cmd_router.suggestions import *
from cmd_router.utils import Status

from .css import style

__all__ = ["Outcome", "REPL"]

Outcome = Status | list[str] | None

class REPL(App[Status]):
    MIN_WIDTH: int
    MIN_HEIGHT: int
    LOG_LIMIT: int
    CSS = style
    BINDINGS: Incomplete
    _handle: Incomplete
    _control_context: Incomplete
    _pending: list[str] | None
    _too_small: bool
    _mounted: bool
    _result_rendered: bool
    _rendered_result: ControlResult | None
    _rendered_json_mode: bool | None
    _rendered_logs: tuple[tuple[int, str], ...]
    def __init__(self, handle: Callable[[str], Outcome], context: Any | None = None) -> None: ...
    def compose(self) -> ComposeResult: ...
    def on_mount(self) -> None: ...
    def on_unmount(self) -> None: ...
    def on_resize(self, event: Resize) -> None: ...
    def on_key(self, event: Key) -> None: ...
    def on_input_changed(self, event: Input.Changed) -> None: ...
    def on_input_submitted(self, event: Input.Submitted) -> None: ...
    def _refresh_views(self) -> None: ...
    def _complete_input(self) -> None: ...
    def _suggestions_for_input(self, command_text: str) -> list[str]: ...
    def _local_suggestions(self, command_text: str) -> list[str] | None: ...
    def _suggestions_server_available(self) -> bool: ...
    def _update_suggestion_line(self, suggestions: list[str] | tuple[str, ...], value: str) -> None: ...
    def _matching_suggestions(self, suggestions: list[str] | tuple[str, ...], value: str) -> list[str]: ...
    @staticmethod
    def _completion_start(value: str, prefix: str = "") -> int: ...
    def _refresh_result_window(self) -> None: ...
    def _refresh_log_window(self) -> None: ...
    def _latest_result(self) -> ControlResult | None: ...
    def _update_size_state(self, width: int, height: int) -> None: ...
    def _set_status(self, message: str, status_class: str) -> None: ...
    def _context_summary(self) -> str: ...
    def _command_placeholder(self) -> str: ...
    def _help_enabled(self) -> bool: ...
    @staticmethod
    def _context_from_handle(handle: Callable[[str], Outcome]) -> Any | None: ...
    def action_quit(self) -> None: ...
