from dataclasses import dataclass
from typing import Final

import click

__all__ = ["flags", "init_flags"]

class _CliCommand(click.Command):
    def main(self, *args, **kwargs): ...

@dataclass
class EnvFlags:
    lazy: bool = ...
    ignore: frozenset[str] = ...
    test_suite: bool = ...
    no_help: bool = ...
    no_suggestions: bool = ...
    max_sized_suggestions: bool = ...
    suggestions_server: bool = ...
    no_suggestions_server: bool = ...
    suggestions_payload: int = ...
    json_out: bool = ...

flags: Final[EnvFlags]

def init_flags(**kwargs) -> None: ...
