from _typeshed import Incomplete
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Final

__all__ = ["paths", "uctx"]

@dataclass
class _Paths:
    @staticmethod
    def _get_root() -> Path: ...
    ROOT: Path = ...
    FIXTURES: Path = ...
    FIXTURES_HTTP: Path = ...
    LOGS_DIR: Path = ...

@dataclass(frozen=True, slots=True)
class _UniversalContext:
    CMD_ROUTER_DEFAULT_ADDRESS: Final[str] = ...
    CMD_ROUTER_DEFAULT_PORT: Final[int] = ...
    INTERNAL_JSON_CONTRACT: Final[dict[str, Any]] = field(default_factory=Incomplete)
    INTERNAL_JSON_CONTRACT_COMPACT: Final[dict[str, Any]] = field(default_factory=Incomplete)
    CMD_ROUTER_SERIAL: Final[str] = ...
    GRAMMAR_SERIAL: Final[str] = ...
    SCHEMA_VERSION_SERIAL: Final[str] = ...
    VALID_SCHEMAS: Final[frozenset[int]] = ...
    SUGGESTIONS_MAX: Final[int] = ...
    SUGGESTION_SERVER_DEFAULT_ADDRESS: Final[str] = ...
    SUGGESTION_SERVER_DEFAULT_PORT: Final[int] = ...

paths: Final[_Paths]
uctx: Final[_UniversalContext]
