from http.server import BaseHTTPRequestHandler

__all__ = ["LazyServer"]

class _LazyHandler(BaseHTTPRequestHandler):
    text: str
    payload: bytes
    def _reply(self, status: int, body: bytes = b"") -> None: ...
    def _invalid(self, message: str) -> None: ...
    def post(self, klass: str) -> None: ...

class LazyServer(_LazyHandler):
    def post(self, klass: str) -> None: ...
    def log_message(self, format, *args) -> None: ...
