from collections.abc import Awaitable, Generator
from threading import RLock
from typing import Any, Final, TextIO

from _typeshed import Incomplete
from prompt_toolkit import HTML

__all__ = ["log_handler", "log"]

class _CompletedWrite:
    def __await__(self) -> Generator[None]: ...

class _LockedStderr:
    _stream: Incomplete
    _lock: Incomplete
    def __init__(self, stream: TextIO, lock: RLock) -> None: ...
    def write(self, text: str) -> int: ...
    def flush(self) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class _StderrWriter:
    _lock: Incomplete
    __latest: str
    def __init__(self, lock: RLock) -> None: ...
    @property
    def _latest(self) -> str: ...
    @_latest.setter
    def _latest(self, v: str) -> None: ...
    def __call__(self, *message: Any, sep: str = " ", end: str = ...) -> Awaitable[None]: ...
    async def async_write(self, *message: Any, sep: str = " ", end: str = ...) -> None: ...
    @property
    def latest_call(self) -> str: ...

class LoggerHandler:
    logger: Incomplete
    _colors: dict[int, str]
    log_id: Incomplete
    _stdout_lock: Incomplete
    _stderr_lock: Incomplete
    _stderr_proxy: _LockedStderr | None
    _stderr_original: TextIO | None
    _stderr_users: int
    def __init__(self) -> None: ...
    def lock_stderr(self) -> None: ...
    def unlock_stderr(self) -> None: ...
    @staticmethod
    def get_final_message(level: int, message: str) -> dict[str, str]: ...
    def html(self, msg: str, level: int = ...) -> HTML: ...
    def log(self, level: int, *message: Any, sep: str, end: str) -> None: ...
    def raw(self, *message: Any, sep: str, end: str) -> None: ...
    @staticmethod
    def _format_message(message: tuple[Any, ...], sep: str) -> str: ...

log_handler: Incomplete

class Logger:
    @staticmethod
    def debug(*message: Any, sep: str = " ", end=...) -> None: ...
    @staticmethod
    def info(*message: Any, sep: str = " ", end=...) -> None: ...
    @staticmethod
    def warning(*message: Any, sep: str = " ", end=...) -> None: ...
    @staticmethod
    def error(*message: Any, sep: str = " ", end=...) -> None: ...
    @staticmethod
    def critical(*message: Any, sep: str = " ", end=...) -> None: ...
    @staticmethod
    def raw(*message: Any, sep: str = " ", end=...) -> None: ...
    stderr: Final[_StderrWriter]
    @staticmethod
    async def stderr_async(*message: Any, sep: str = " ", end=...) -> None: ...

log: Incomplete
