from _typeshed import Incomplete
from collections.abc import Awaitable, Generator
from prompt_toolkit import HTML
from threading import RLock
from typing import Any, Final, TextIO

__all__ = ["log_handler", "log"]

class _CompletedWrite:
    def __await__(self) -> Generator[None]: ...

class _LockedStderr:
    def __init__(self, stream: TextIO, lock: RLock) -> None: ...
    def write(self, text: str) -> int: ...
    def flush(self) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class _StderrWriter:
    def __init__(self, lock: RLock) -> None: ...
    def __call__(self, *message: Any, sep: str = " ", end: str = "\n") -> Awaitable[None]: ...
    async def async_write(self, *message: Any, sep: str = " ", end: str = "\n") -> None: ...
    @property
    def latest_call(self) -> str: ...

class LoggerHandler:
    logger: Incomplete
    log_id: Incomplete
    def __init__(self) -> None: ...
    def lock_stderr(self) -> None: ...
    def unlock_stderr(self) -> None: ...
    @staticmethod
    def get_final_message(level: int, message: str) -> dict[str, str]: ...
    def html(self, msg: str, level: int = ...) -> HTML: ...
    def log(self, level: int, *message: Any, sep: str, end: str) -> None: ...
    def raw(self, *message: Any, sep: str, end: str) -> None: ...

log_handler: Incomplete

class Logger:
    @staticmethod
    def debug(*message: Any, sep: str = " ", end: str = "\n") -> None: ...
    @staticmethod
    def info(*message: Any, sep: str = " ", end: str = "\n") -> None: ...
    @staticmethod
    def warning(*message: Any, sep: str = " ", end: str = "\n") -> None: ...
    @staticmethod
    def error(*message: Any, sep: str = " ", end: str = "\n") -> None: ...
    @staticmethod
    def critical(*message: Any, sep: str = " ", end: str = "\n") -> None: ...
    @staticmethod
    def raw(*message: Any, sep: str = " ", end: str = "\n") -> None: ...
    stderr: Final[_StderrWriter]
    @staticmethod
    async def stderr_async(*message: Any, sep: str = " ", end: str = "\n") -> None: ...

log: Incomplete
