from dataclasses import dataclass
from typing import Final

__all__ = ["Status", "IStatus", "stat"]

@dataclass(frozen=True)
class _StatusContract:
    _MESSAGE: str | None = ...
    _EXPECTED: str | None = ...
    _code: int = ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def code(self) -> int: ...
    @property
    def message(self) -> str: ...
    @property
    def expected(self) -> str: ...

Status = _StatusContract
IStatus: Final[type[Status]]

class _StatusNS:
    class Success(IStatus):
        _code: int

    class Abort(IStatus):
        _code: int

    class Interrupted(IStatus):
        _code: int

    class ImpossibleControlState(IStatus): ...
    class DefaultGrammarError(IStatus): ...
    class GrammarLoadError(IStatus): ...
    class InvalidGrammarError(IStatus): ...
    class UnsupportedGrammarFormatError(IStatus): ...
    class TokenizeInvalidError(IStatus): ...
    class TokenizeUnsupportedTypeError(IStatus): ...
    class ControlNotInitializedError(IStatus): ...
    class ControlFixtureError(IStatus): ...
    class ControlGrammarError(IStatus): ...
    class ControlActionError(IStatus): ...
    class ArgumentParseError(IStatus): ...
    class FixtureInitializationError(IStatus): ...

stat: Final[_StatusNS]
