from dataclasses import dataclass
from typing import Final

__all__ = ["Status", "IStatus", "stat"]

@dataclass(frozen=True)
class _StatusContract:
    _MESSAGE: str | None = ...
    _EXPECTED: str | None = ...
    _code: int | None = ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def code(self) -> int: ...
    @property
    def message(self) -> str: ...
    @property
    def expected(self) -> str: ...

Status = _StatusContract
IStatus: Final[type[Status]]

class _StatusNS:
    class Success(_StatusContract):
        _code: int

    class Abort(_StatusContract):
        _code: int

    class Interrupted(_StatusContract):
        _code: int

    class DefaultGrammarError(_StatusContract): ...
    class GrammarLoadError(_StatusContract): ...
    class InvalidGrammarError(_StatusContract): ...
    class UnsupportedGrammarFormatError(_StatusContract): ...
    class TokenizeInvalidError(_StatusContract): ...
    class TokenizeUnsupportedTypeError(_StatusContract): ...
    class ControlNotInitializedError(_StatusContract): ...
    class ControlFixtureError(_StatusContract): ...
    class ControlGrammarError(_StatusContract): ...
    class ControlActionError(_StatusContract): ...
    class ArgumentParseError(_StatusContract): ...
    class FixtureInitializationError(_StatusContract): ...

stat: Final[_StatusNS]
