from dataclasses import dataclass
from typing import Final

__all__ = ["StatusType", "Status", "stat"]

@dataclass(frozen=True)
class _BaseStatus:
    _MESSAGE: str | None = ...
    _EXPECTED: str | None = ...
    def __str__(self) -> str: ...
    @property
    def message(self) -> str: ...
    @property
    def expected(self) -> str: ...
    @property
    def name(self) -> str: ...

StatusType = _BaseStatus
Status: Final[type[StatusType]]

class _Status:
    class Abort(_BaseStatus): ...
    class Success(_BaseStatus): ...
    class DefaultGrammarError(_BaseStatus): ...
    class GrammarLoadError(_BaseStatus): ...
    class InvalidGrammarError(_BaseStatus): ...
    class UnsupportedGrammarFormatError(_BaseStatus): ...
    class TokenizeInvalidError(_BaseStatus): ...
    class TokenizeUnsupportedTypeError(_BaseStatus): ...
    class ControlNotInitializedError(_BaseStatus): ...
    class ControlFixtureError(_BaseStatus): ...
    class ControlGrammarError(_BaseStatus): ...
    class ControlActionError(_BaseStatus): ...
    class Interrupted(_BaseStatus): ...
    class ArgumentParseError(_BaseStatus): ...
    class FixtureInitializationError(_BaseStatus): ...

stat: Final[_Status]
