from functools import lru_cache

import click

from .env_flags import flags as flags

__all__ = ["flags", "normalize_bare_options", "flag_names", "cli_flags", "describe_flags", "init_flags"]

class _CliCommand(click.Command):
    def main(self, *args, **kwargs): ...

def normalize_bare_options(args: list[str]) -> list[str]: ...
def flag_names() -> tuple[str, ...]: ...
@lru_cache
def cli_flags(field: str) -> tuple[str, ...]: ...
@lru_cache
def describe_flags(name: str | None) -> str: ...
def init_flags(**kwargs) -> None: ...
