from dataclasses import dataclass
from pathlib import Path
from typing import Final

__all__ = ["flags"]

@dataclass
class __EnvFlags:
    verbose_help: str | None = ...
    init: Path | None = ...
    lazy: bool = ...
    ignore: frozenset[str] = ...
    test_suite: bool = ...
    serve: bool = ...
    quiet: bool = ...
    genesis: Path | None = ...
    no_help: bool = ...
    no_suggestions: bool = ...
    max_sized_suggestions: bool = ...
    suggestions_server: bool = ...
    no_suggestions_server: bool = ...
    suggestions_payload: int = ...
    json_out: bool = ...

flags: Final[__EnvFlags]
