from collections.abc import Callable
from types import ModuleType
from typing import Any

from _typeshed import Incomplete

from cmd_router.lib.commands.dispatcher import CommandDispatcher

from .fixtures_api import FixturesSetup
from .result import ControlInitialization, ControlResult

__all__ = ["ControlDeeperContext"]

_Action = Callable[..., Any]

class ControlDeeperContext:
    _setup: Incomplete
    dispatcher: CommandDispatcher
    grammars: dict[str, str]
    fixture_module: ModuleType | None
    fixture_logic: Any
    initialized: bool
    last_result: ControlResult | None
    last_initialization: ControlInitialization | None
    def __init__(self, setup: FixturesSetup | None = None) -> None: ...
    @property
    def setup(self) -> FixturesSetup: ...
    @property
    def context(self) -> FixturesSetup: ...
    @context.setter
    def context(self, value: FixturesSetup) -> None: ...
    @property
    def fixture_setup(self) -> FixturesSetup: ...
    def _replace_setup(self, value: FixturesSetup) -> None: ...
    def attach_fixture(self, module: ModuleType, logic: Any, setup: FixturesSetup) -> None: ...
    @property
    def cmd_prefix(self) -> str: ...
    @cmd_prefix.setter
    def cmd_prefix(self, value: str) -> None: ...
    @property
    def lazy_init_help(self) -> bool: ...
    @lazy_init_help.setter
    def lazy_init_help(self, value: bool) -> None: ...
    @property
    def command_args_ctrl(self) -> dict[str, Any]: ...
    @command_args_ctrl.setter
    def command_args_ctrl(self, value: dict[str, Any]) -> None: ...
    @property
    def command_action(self) -> dict[str, _Action]: ...
    @command_action.setter
    def command_action(self, value: dict[str, _Action]) -> None: ...
    def set_command_args(self, command: str, **arguments: Any) -> None: ...
    def clear_command_args(self, command: str | None = None) -> None: ...
