from .context import _DeeperLevelContext
from .fixtures import FixturesSetup
from .result import ControlInitialization, ControlResult
from asyncio import Lock
from cmd_router.lib.command import CmdParse
from cmd_router.lib.control.compiler import _GrammarSource
from collections.abc import Callable, Mapping
from dataclasses import dataclass
from pathlib import Path
from types import ModuleType
from typing import Any, Self

__all__ = ["Control"]

_Action = Callable[..., Any]

@dataclass(frozen=True, slots=True)
class _Invocation:
    command: str
    parsed: CmdParse.Result
    context: CmdParse.Context
    handler: _Action

class Control:
    deeper_level: _DeeperLevelContext
    _async_lock: Lock
    _stderr_locked: bool
    def __init__(self, *, setup: FixturesSetup | None = None, deeper: _DeeperLevelContext | None = None) -> None: ...
    @property
    def context(self) -> FixturesSetup: ...
    @property
    def deeper(self) -> _DeeperLevelContext: ...
    def initialize(
        self,
        grammars: _GrammarSource | None = None,
        *,
        fixture: ModuleType | str | Path | None = None,
        keep_help: bool | None = None,
    ) -> ControlInitialization: ...
    def configure(self, grammars: _GrammarSource) -> ControlInitialization: ...
    def _initialize_fixture(self, fixture: ModuleType | str | Path) -> ControlInitialization: ...
    def _initialization_error(
        self, message: str, exception: Exception | None = None, code: int = ...
    ) -> ControlInitialization: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, *_arguments: Any) -> None: ...
    def execute(self, command: Any) -> ControlResult: ...
    dispatch = execute
    async def execute_async(self, command: Any) -> ControlResult: ...
    async_dispatch = execute_async
    aexecute = execute_async
    def _execute_sync(self, command: Any) -> ControlResult: ...
    def _prepare(self, command: Any) -> ControlResult | _Invocation: ...
    def _controlled_arguments(self, command: str, arguments: Mapping[str, Any]) -> dict[str, Any]: ...
    def _remember(self, result: ControlResult) -> ControlResult: ...
