from collections.abc import Callable
from dataclasses import dataclass
from typing import Any, ClassVar, Self

from _typeshed import Incomplete

from cmd_router.suggestions.context import *
from cmd_router.utils import Status

__all__ = ["FixtureInitializationError", "FixturesContextHolder", "FixturesSetup"]

_Action = Callable[..., Any]
FixtureInitializationError: Incomplete

@dataclass(slots=True)
class _FixtureInnerContext:
    did_context_holder_ever_initialize: bool = ...
    did_fixture_setup_ever_initialize: bool = ...
    @staticmethod
    def reset() -> None: ...
    @staticmethod
    def validate() -> None | Status: ...

class FixturesContextHolder:
    _current: ClassVar[Self | None]
    calls: list[tuple[str, dict[str, Any]]]
    def __init__(self) -> None: ...
    @classmethod
    def current(cls) -> Self | None: ...
    def _record(self, name: str, arguments: dict[str, Any]) -> dict[str, Any]: ...

class FixturesSetup:
    logic: Any
    _active_suggestions_size: ClassVar[int | None]
    _cmd_prefix: Incomplete
    _lazy_init_help: bool
    _command_action: dict[str, _Action]
    _command_args_ctrl: dict[str, Any]
    _suggestions_size: int
    def __init__(self, logic: Any = None) -> None: ...
    @classmethod
    def _resolve_suggestions_limit(cls) -> int: ...
    @staticmethod
    def __typerror__(name: str, value: Any, expected: type[Any]) -> TypeError: ...
    @property
    def cmd_prefix(self) -> str: ...
    @cmd_prefix.setter
    def cmd_prefix(self, v: str) -> None: ...
    @property
    def lazy_init_help(self) -> bool: ...
    @lazy_init_help.setter
    def lazy_init_help(self, v: bool) -> None: ...
    @property
    def command_action(self) -> dict[str, _Action]: ...
    @command_action.setter
    def command_action(self, v: dict[str, _Action]) -> None: ...
    @property
    def command_args_ctrl(self) -> dict[str, Any]: ...
    @command_args_ctrl.setter
    def command_args_ctrl(self, v: dict[str, Any]) -> None: ...
    @property
    def suggestions_max_list_size(self) -> int: ...
    @property
    def suggestions_get_size(self) -> int: ...
    @property
    def suggestions_set_current_size(self) -> int: ...
    @suggestions_set_current_size.setter
    def suggestions_set_current_size(self, v: int) -> None: ...
    @property
    def suggestions_server_address(self) -> str: ...
    @suggestions_server_address.setter
    def suggestions_server_address(self, v: str) -> None: ...
    @property
    def suggestions_server_port(self) -> int: ...
    @suggestions_server_port.setter
    def suggestions_server_port(self, v: int) -> None: ...
