from typing import Any, Self

__all__ = ["FixturesContextHolder", "FixturesSetup"]

class FixturesContextHolder:
    calls: list[tuple[str, dict[str, Any]]]
    def __init__(self) -> None: ...
    @classmethod
    def current(cls) -> Self | None: ...

class FixturesSetup:
    logic: Any
    def __init__(self, logic: Any = None) -> None: ...
    @staticmethod
    def __typerror__(name: str, value: Any, expected: type[Any]) -> TypeError: ...
    @property
    def cmd_prefix(self) -> str: ...
    @cmd_prefix.setter
    def cmd_prefix(self, v: str) -> None: ...
    @property
    def control_no_help_keeps_help(self) -> bool: ...
    @control_no_help_keeps_help.setter
    def control_no_help_keeps_help(self, v: bool) -> None: ...
    @property
    def command_action(self) -> dict[str, _Action]: ...
    @command_action.setter
    def command_action(self, v: dict[str, _Action]) -> None: ...
    @property
    def command_args_ctrl(self) -> dict[str, Any]: ...
    @command_args_ctrl.setter
    def command_args_ctrl(self, v: dict[str, Any]) -> None: ...
