from _typeshed import Incomplete
from collections.abc import Callable
from typing import Any, ClassVar, Self

__all__ = ["FixturesContextHolder", "FixturesSetup"]

_Action = Callable[..., Any]

class FixturesContextHolder:
    _current: ClassVar[Self | None]
    calls: list[tuple[str, dict[str, Any]]]
    def __init__(self) -> None: ...
    @classmethod
    def current(cls) -> Self | None: ...
    def _record(self, name: str, arguments: dict[str, Any]) -> dict[str, Any]: ...

class FixturesSetup:
    logic: Any
    _cmd_prefix: Incomplete
    _control_no_help_keeps_help: bool
    _command_action: dict[str, _Action]
    _command_args_ctrl: dict[str, Any]
    def __init__(self, logic: Any = None) -> None: ...
    @staticmethod
    def __typerror__(name: str, value: Any, expected: type[Any]) -> TypeError: ...
    @property
    def cmd_prefix(self) -> str: ...
    @cmd_prefix.setter
    def cmd_prefix(self, v: str) -> None: ...
    @property
    def control_no_help_keeps_help(self) -> bool: ...
    @control_no_help_keeps_help.setter
    def control_no_help_keeps_help(self, v: bool) -> None: ...
    @property
    def command_action(self) -> dict[str, _Action]: ...
    @command_action.setter
    def command_action(self, v: dict[str, _Action]) -> None: ...
    @property
    def command_args_ctrl(self) -> dict[str, Any]: ...
    @command_args_ctrl.setter
    def command_args_ctrl(self, v: dict[str, Any]) -> None: ...
