from pathlib import Path
from typing import Any

from _typeshed import Incomplete

from command_router.lib.control import ControlResult
from command_router.lib.control.api import *
from command_router.lib.grammar.loader import *
from command_router.suggestions import *
from command_router.suite import *
from command_router.utils import Status
from command_router.utils import init_flags as init_flags

__all__ = ["init_flags", "start", "Lazy@85"]

_Dict = dict[str, Any]

class __Router:
    grammars: _Dict
    info: _Dict
    control: Incomplete
    def normalize(self, *t: _Dict) -> None: ...
    def lazy_init(self) -> None: ...
    def grammar_init(self, f: list[Path] | Path) -> tuple[_Dict, _Dict] | Status: ...
    @property
    def genesis_source(self) -> Path | None: ...
    def control_init(self) -> bool: ...

class __CommandRouter:
    _was_i_initialized: bool
    _grammars: Incomplete
    _info: Incomplete
    control: Incomplete
    def __init__(self) -> None: ...
    @property
    def initialize(self) -> Status: ...
    @property
    def main(self) -> Status: ...
    def execute(self, command: Any) -> ControlResult: ...
    async def execute_async(self, command: Any) -> ControlResult: ...
    @property
    def deeper_level(self) -> Any: ...
    def _test_suite_loop(self) -> Status: ...
    def _serve_loop(self) -> Status: ...
    @staticmethod
    def _serve_fallback(text: str, message: str) -> None: ...
    def _verbose_help(self, name: str) -> Status: ...
    def _scaffold(self, dest: Path | None) -> Status: ...
    def _handle_command(self, command: str) -> Outcome: ...

def start(entry: tuple[str, ...] | None = None) -> Status: ...

# Names in __all__ with no definition:
#   Lazy@85
