from cmd_router.lib.control.api.result import ControlResultKinds
from collections.abc import Callable
from dataclasses import dataclass, field
from typing import Any, Final

__all__ = ["cmd_ctx", "ParseErrorKinds", "CommandContext", "ParseError", "ParseResult"]

_Handler = Callable[..., Any]

@dataclass
class _CommandContext: ...

cmd_ctx: Final[_CommandContext]
ParseErrorKinds: Final[type[ControlResultKinds]]

@dataclass(frozen=True, slots=True)
class CommandContext:
    input: str
    args: dict[str, Any]
    cursor: int
    tokens: tuple[str, ...]
    @property
    def original_input(self) -> str: ...
    @property
    def parsed_args(self) -> dict[str, Any]: ...
    def get(self, name: str, default: Any = None) -> Any: ...

@dataclass(frozen=True, slots=True)
class ParseError:
    kind: ParseErrorKinds
    token_index: int
    expected: tuple[str, ...] = ...
    message: str = ...
    partial_args: dict[str, Any] = field(default_factory=dict)
    code: int | None = ...
    @property
    def position(self) -> int: ...
    @property
    def expectations(self) -> tuple[str, ...]: ...
    @property
    def cursor(self) -> int: ...
    @property
    def parsed_args(self) -> dict[str, Any]: ...
    def to_dict(self) -> dict[str, Any]: ...
    as_dict = to_dict

@dataclass(frozen=True, slots=True)
class ParseResult:
    handler: _Handler | None = ...
    context: CommandContext | None = ...
    error: ParseError | None = ...
    @property
    def ok(self) -> bool: ...
    @property
    def success(self) -> bool: ...
