[project]
name = "lib"
version = "0.0.1-dev"
requires-python = ">=3.14.6"
license = "BSD-3-Clause-Clear"
authors = [
    { name = "dennis", email = "dcxrpse@krwwstudios.com" }
]
description = "<TBA>"
readme = "readme.md"
# "dependencies" should be met at root.

[build-system]
requires = ["uv_build>=0.11.29,<0.12.0"]
build-backend = "uv_build"
