from dataclasses import dataclass
from typing import Any

from _typeshed import Incomplete

from cmd_router.utils import log as log

class _GrammarSyntaxError(ValueError): ...

@dataclass(frozen=True, slots=True)
class _LiteralTerm:
    value: str

@dataclass(frozen=True, slots=True)
class _ArgumentTerm:
    name: str
    type_name: str
    default: Any = ...
    has_default: bool = ...

@dataclass(frozen=True, slots=True)
class _ChoiceTerm:
    alternatives: tuple[tuple[Any, ...], ...]

@dataclass(frozen=True, slots=True)
class _OptionalTerm:
    body: _ChoiceTerm

class _GrammarParser:
    _tokens: Incomplete
    _position: int
    def __init__(self, source: str) -> None: ...
    def parse(self) -> tuple[Any, ...]: ...
    def _parse_alternatives(self, closing: str | None) -> tuple[tuple[Any, ...], ...]: ...
    def _parse_sequence(self, closing: str | None) -> tuple[Any, ...]: ...
    def _parse_term(self) -> Any: ...
    @staticmethod
    def _scan(source: str) -> tuple[str, ...]: ...
    @staticmethod
    def _parse_argument(token: str) -> _ArgumentTerm: ...
    def _peek(self) -> str | None: ...
    def _take(self) -> str: ...
    def _expect(self, expected: str) -> None: ...
