from dataclasses import dataclass
from pathlib import Path
from typing import Final

import click

__all__ = ["flags", "normalize_bare_options", "flag_names", "describe_flags", "init_flags"]

class _CliCommand(click.Command):
    def main(self, *args, **kwargs): ...

@dataclass
class EnvFlags:
    verbose_help: str | None = ...
    init: Path | None = ...
    lazy: bool = ...
    ignore: frozenset[str] = ...
    test_suite: bool = ...
    serve: bool = ...
    quiet: bool = ...
    genesis: Path | None = ...
    no_help: bool = ...
    no_suggestions: bool = ...
    max_sized_suggestions: bool = ...
    suggestions_server: bool = ...
    no_suggestions_server: bool = ...
    suggestions_payload: int = ...
    json_out: bool = ...

flags: Final[EnvFlags]

def normalize_bare_options(args: list[str]) -> list[str]: ...
def flag_names() -> tuple[str, ...]: ...
def describe_flags(name: str | None) -> str: ...
def init_flags(**kwargs) -> None: ...
